name: SSH via tmate

on:
  push:
    branches:
      - main
  workflow_dispatch: # Memungkinkan menjalankan workflow secara manual

jobs:
  tmate-ssh:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install tmate
      - name: Install tmate
        run: |
          sudo apt-get update
          sudo apt-get install -y tmate

      # Start tmate session and output the connection string
      - name: Start tmate session
        run: |
          tmate -v
          tmate new-session -d
          echo "tmate session started. Use the following command to connect:"
          tmate show-messages
          
      # Keep the session alive (this will prevent workflow from finishing)
      - name: Keep tmate session alive
        run: sleep infinity
        
